### ISSUE TITLE
Netlify Integration

### ISSUE THREAD

**Issue by vincent-h-lee** [vincent-h-lee/portfolio-site#4]
## Tasks 

- [x] Create Netlify project
- [x] Source data from Netlify
- [x] Set up build on Netlify
